apiVersion: extensions.kubesphere.io/v1alpha1
kind: ReverseProxy
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: databend-playground
  name: databend-playground
spec:
  directives:
    headerUp:
    - -Authorization
    stripPathPrefix: /proxy/databend.playground
  matcher:
    method: '*'
    path: /proxy/databend.playground/*
  upstream:
    url: http://databend-playground.default.svc:4000
status:
  state: Available
