kind: ConfigMap
apiVersion: v1
metadata:
  name: databend-playground-js-bundle
  namespace: extension-databend-playground
data:
  index.js: >
    System.register(["@kubed/components","lodash","react"],(function(e,t){var
    r={},n={},o={};return{setters:[function(e){r.Loading=e.Loading},function(e){n.get=e.get},function(e){o.default=e.default,o.useRef=e.useRef,o.useState=e.useState}],execute:function(){e(function(){var
    e={104:function(e,t,r){var n={"./base.json":12};function o(e){var
    t=a(e);return r(t)}function a(e){if(!r.o(n,e)){var t=new Error("Cannot find
    module '"+e+"'");throw t.code="MODULE_NOT_FOUND",t}return
    n[e]}o.keys=function(){return
    Object.keys(n)},o.resolve=a,e.exports=o,o.id=104},863:function(e,t,r){var
    n={"./base.json":242};function o(e){var t=a(e);return r(t)}function
    a(e){if(!r.o(n,e)){var t=new Error("Cannot find module '"+e+"'");throw
    t.code="MODULE_NOT_FOUND",t}return n[e]}o.keys=function(){return
    Object.keys(n)},o.resolve=a,e.exports=o,o.id=863},386:function(e,t,r){var
    n=r(149).R;t.s=function(e){if(e||(e=1),!r.y.meta||!r.y.meta.url)throw
    console.error("__system_context__",r.y),Error("systemjs-webpack-interop was
    provided an unknown SystemJS context. Expected context.meta.url, but none
    was provided");r.p=n(r.y.meta.url,e)}},149:function(e,t,r){function
    n(e,t){var r=document.createElement("a");r.href=e;for(var
    n="/"===r.pathname[0]?r.pathname:"/"+r.pathname,o=0,a=n.length;o!==t&&a>=0;){"/"===n[--a]&&o++}if(o!==t)throw
    Error("systemjs-webpack-interop: rootDirectoryLevel ("+t+") is greater than
    the number of directories ("+o+") in the URL path "+e);var
    i=n.slice(0,a+1);return r.protocol+"//"+r.host+i}t.R=n;var
    o=Number.isInteger||function(e){return"number"==typeof
    e&&isFinite(e)&&Math.floor(e)===e}},586:function(e){"use
    strict";e.exports=r},978:function(e){"use
    strict";e.exports=n},954:function(e){"use
    strict";e.exports=o},12:function(e){"use
    strict";e.exports={name:"Name"}},242:function(e){"use
    strict";e.exports={name:"名称"}}},a={};function i(t){var r=a[t];if(void
    0!==r)return r.exports;var n=a[t]={exports:{}};return
    e[t](n,n.exports,i),n.exports}i.y=t,i.g=function(){if("object"==typeof
    globalThis)return globalThis;try{return this||new Function("return
    this")()}catch(e){if("object"==typeof window)return
    window}}(),i.o=function(e,t){return
    Object.prototype.hasOwnProperty.call(e,t)},i.r=function(e){"undefined"!=typeof
    Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},function(){var
    e;i.g.importScripts&&(e=i.g.location+"");var
    t=i.g.document;if(!e&&t&&(t.currentScript&&(e=t.currentScript.src),!e)){var
    r=t.getElementsByTagName("script");r.length&&(e=r[r.length-1].src)}if(!e)throw
    new Error("Automatic publicPath is not supported in this
    browser");e=e.replace(/#.*$/,"").replace(/\?.*$/,"").replace(/\/[^\/]+$/,"/"),i.p=e}();var
    c={};return(0,i(386).s)(1),function(){"use strict";function e(e,t,r){return
    t in
    e?Object.defineProperty(e,t,{value:r,enumerable:!0,configurable:!0,writable:!0}):e[t]=r,e}function
    t(e,t){var r=Object.keys(e);if(Object.getOwnPropertySymbols){var
    n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return
    Object.getOwnPropertyDescriptor(e,t).enumerable}))),r.push.apply(r,n)}return
    r}function r(r){for(var n=1;n<arguments.length;n++){var
    o=null!=arguments[n]?arguments[n]:{};n%2?t(Object(o),!0).forEach((function(t){e(r,t,o[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(r,Object.getOwnPropertyDescriptors(o)):t(Object(o)).forEach((function(e){Object.defineProperty(r,e,Object.getOwnPropertyDescriptor(o,e))}))}return
    r}i.r(c);for(var
    n=i(863),o=n.keys().filter((function(e){return"./index.ts"!==e})),a={},u=0;u<o.length;u+=1)o[u].startsWith(".")&&(a=r(r({},a),n(o[u])));var
    s=a;function l(e,t){var
    r=Object.keys(e);if(Object.getOwnPropertySymbols){var
    n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return
    Object.getOwnPropertyDescriptor(e,t).enumerable}))),r.push.apply(r,n)}return
    r}function f(t){for(var r=1;r<arguments.length;r++){var
    n=null!=arguments[r]?arguments[r]:{};r%2?l(Object(n),!0).forEach((function(r){e(t,r,n[r])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):l(Object(n)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))}))}return
    t}for(var
    p=i(104),y=p.keys().filter((function(e){return"./index.ts"!==e})),d={},b=0;b<y.length;b+=1)y[b].startsWith(".")&&(d=f(f({},d),p(y[b])));var
    g={zh:s,en:d},m=i(954);function
    h(e,t){(null==t||t>e.length)&&(t=e.length);for(var r=0,n=new
    Array(t);r<t;r++)n[r]=e[r];return n}function v(e,t){return
    function(e){if(Array.isArray(e))return e}(e)||function(e,t){var
    r=null==e?null:"undefined"!=typeof
    Symbol&&e[Symbol.iterator]||e["@@iterator"];if(null!=r){var
    n,o,a=[],i=!0,c=!1;try{for(r=r.call(e);!(i=(n=r.next()).done)&&(a.push(n.value),!t||a.length!==t);i=!0);}catch(u){c=!0,o=u}finally{try{i||null==r.return||r.return()}finally{if(c)throw
    o}}return a}}(e,t)||function(e,t){if(e){if("string"==typeof e)return
    h(e,t);var
    r=Object.prototype.toString.call(e).slice(8,-1);return"Object"===r&&e.constructor&&(r=e.constructor.name),"Map"===r||"Set"===r?Array.from(e):"Arguments"===r||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(r)?h(e,t):void
    0}}(e,t)||function(){throw new TypeError("Invalid attempt to destructure
    non-iterable instance.\nIn order to be iterable, non-array objects must have
    a [Symbol.iterator]() method.")}()}var O=i(978),w=i(586);function j(){var
    e=v((0,m.useState)(!0),2),t=e[0],r=e[1],n=(0,m.useRef)();return
    m.default.createElement(m.default.Fragment,null,t&&m.default.createElement(w.Loading,{className:"page-loading"}),m.default.createElement("iframe",{ref:n,src:"/proxy/databend.playground/",width:"100%",height:"100%",style:{height:"calc(100vh
    - 68px)",display:t?"none":"block"},onLoad:function(){var
    e=(0,O.get)(n.current,"contentWindow.document");if(e){var
    t=e.querySelector("#root > section >
    aside");t&&(t.style.display="none")}r(!1)}}))}var
    S={routes:[{path:"/databend-playground",element:m.default.createElement(j,null)}],menus:[{parent:"global",name:"databend-playground",title:"Databend
    Playground",icon:"cluster",order:0,desc:"Databend Playground provides a
    one-stop solution for deployment, operation, and query visualization of
    Databend.",skipAuth:!0}],locales:g};globals.context.registerExtension(S)}(),c}())}}}));

---
apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: databend-playground
spec:
  rawFrom:
    configMapKeyRef:
      key: index.js
      name: databend-playground-js-bundle
      namespace: extension-databend-playground
status:
  link: /dist/databend-playground/index.js
  state: Available
