apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: createbuckets
  name: createbuckets
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: createbuckets
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: createbuckets
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' /usr/bin/mc config host add databendminio http://databend-minio:9000 minioadmin minioadmin; /usr/bin/mc rm -r --force databendminio/databend; /usr/bin/mc mb databendminio/databend; /usr/bin/mc policy download databendminio/minioadmin; exit 0; '
          image: minio/mc
          name: createbuckets
          resources: {}
      restartPolicy: Always
status: {}
